### ISSUE TITLE
License

### ISSUE THREAD

**Issue by geezacoleman** [Aqib-Soft-Solutions/Wheat-Crop-Weeds-Dataset#1]
Thanks for producing a great dataset (and sharing it!) and paper. What is the license on these images, can I use them for my own research project?

**Comment by Muhammad-Ali-Saqib** [comment]
Certainly! You are welcome to use the dataset for your own research project. However, please make sure to properly cite both the research article and the dataset as sources of your data. This helps acknowledge the original creators and contributes to the transparency and reproducibility of research. If you have any specific guidelines or requirements for citation, please let me know, and I'll be happy to assist further.

**Citation:**
```
@ARTICLE{10.3389/fpls.2023.1211235,
	AUTHOR={Saqib, Muhammad Ali and Aqib, Muhammad and Tahir, Muhammad Naveed and Hafeez, Yaser},   
	TITLE={Towards deep learning based smart farming for intelligent weeds management in crops},      
	JOURNAL={Frontiers in Plant Science},      
	VOLUME={14},           
	YEAR={2023},      
	URL={https://www.frontiersin.org/articles/10.3389/fpls.2023.1211235},       
	DOI={10.3389/fpls.2023.1211235},      
	ISSN={1664-462X}
}
```
